apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-backstage
  namespace: backstage
spec:
  instances: 3

  imageName: ghcr.io/cloudnative-pg/postgresql:16

  storage:
    size: 8Gi

  resources:
    requests:
      cpu: "150m"
      memory: "384Mi"
    limits:
      cpu: "150m"
      memory: "384Mi"

  bootstrap:
    initdb:
      database: backstagedb
      owner: backstageuser
      postInitSQL:
        - "ALTER ROLE backstageuser CREATEDB;"

  postgresql:
    parameters:
      max_connections: "30"
      shared_buffers: "64MB"
  
  monitoring:
    enablePodMonitor: true